"use strict";
(() => {
  const make = (tag, cls, text) => { const n=document.createElement(tag); if(cls)n.className=cls; if(text!==undefined)n.textContent=text; return n; };
  const fmt = (v,d=2) => typeof v==='number' && Number.isFinite(v) ? v.toLocaleString('zh-CN',{maximumFractionDigits:d}) : '未确认';
  const clone = v => JSON.parse(JSON.stringify(v));
  const pct = v => fmt(v*100,2)+'%';
  const btn = (text,fn) => {const n=make('button','button button-secondary',text);n.type='button';n.addEventListener('click',fn);return n;};
  const table = (heads,rows) => {const wrap=make('div','color-table-wrap'),t=make('table','color-table'),h=make('tr');heads.forEach(x=>h.append(make('th','',x)));const th=make('thead');th.append(h);t.append(th);const b=make('tbody');rows.forEach(row=>{const tr=make('tr');row.forEach(x=>tr.append(make('td','',x)));b.append(tr);});t.append(b);wrap.append(t);return wrap;};
  class ColorView {
    constructor(root,hooks) {
      this.root=root;this.h=hooks;this.sequence=0;this.caseSequence=0;this.budget=null;this.case=null;this.casesLoaded=false;
      const head=make('div','page-heading'),copy=make('div');copy.append(make('div','eyebrow','RGB MIXING · WHITE POINT · BRIGHTNESS'),make('h1','','配色与亮度'),make('p','','从已核读表格到可修改、可复算的原型预算。'));head.append(copy);
      this.status=make('span','save-status');this.picker=make('select');this.picker.setAttribute('aria-label','配色当前原型');this.picker.addEventListener('change',()=>this.h.select(this.picker.value));this.save=btn('保存配色到当前原型',()=>this.h.save());this.save.className='button button-dark';
      const bar=make('div','color-toolbar');bar.append(make('strong','','当前原型'),this.picker,this.status,this.save,btn('查看光路 ↗',()=>this.h.navigate('workspace')));
      const casePanel=make('section','panel color-panel');casePanel.append(make('h2','','已核读表格 · 对照与问题'));this.casePicker=make('select');this.casePicker.setAttribute('aria-label','配色表格案例');this.casePicker.addEventListener('change',()=>this.readCase(this.casePicker.value));this.useCase=btn('载入此案例到当前原型',()=>this.applyCase());const cb=make('div','color-toolbar');cb.append(this.casePicker,this.useCase);this.caseBody=make('div');casePanel.append(cb,this.caseBody);
      const grid=make('div','color-grid');this.editor=make('section','panel color-panel');this.results=make('section','panel color-panel color-results');grid.append(this.editor,this.results);root.append(head,bar,casePanel,grid);
    }
    async load(project) {
      this.sequence++;clearTimeout(this.timer);this.budget=null;this.result=null;this.results.replaceChildren(make('p','','正在读取配色预算…'));
      const seq=this.sequence;
      if(!this.casesLoaded){this.casesLoaded=true;try {const cases=await this.h.api('/api/color/cases');cases.forEach(c=>{const o=make('option','',c.title);o.value=c.id;this.casePicker.append(o);});this.casePicker.value=cases.some(c=>c.id==='sst-2')?'sst-2':cases[0]?.id;this.readCase(this.casePicker.value);}catch(e){this.casesLoaded=false;this.caseBody.textContent=e.message;}}
      try {const data=await this.h.api(`/api/projects/${project.id}/color`);if(seq!==this.sequence)return;this.budget=clone(project.color_budget||data.budget);this.renderEditor();this.preview();}catch(e){if(seq===this.sequence)this.results.textContent=e.message;}
      this.update();
    }
    update(){const s=this.h.state();this.picker.replaceChildren(...s.projects.map(p=>{const o=make('option','',p.name);o.value=p.id;return o;}));this.picker.value=s.project?.id||'';this.status.textContent=s.dirty?'● 有未保存修改':s.project?`已保存 · v${s.project.version}`:'尚未载入';this.save.disabled=!s.project||s.busy||!s.project.color_budget;this.useCase.disabled=!s.project||s.busy||!this.case;this.picker.disabled=s.busy;this.editor.querySelectorAll('input,select,button').forEach(n=>n.disabled=s.busy||!s.project);}
    changed(){if(!this.budget||!this.h.state().project)return;this.h.edit(clone(this.budget));this.sequence++;clearTimeout(this.timer);this.results.replaceChildren(make('p','','参数已变更，正在复算…'));this.timer=setTimeout(()=>this.preview(),230);}
    field(parent,label,obj,key,options=null,nullable=false){const wrap=make('label','color-field'),n=make(options?'select':'input');wrap.append(make('span','',label));n.setAttribute('aria-label',label);if(options){options.forEach(([value,text])=>{const o=make('option','',text);o.value=value;n.append(o);});n.value=obj[key];}else{n.type=typeof obj[key]==='string'?'text':'number';n.step='any';n.value=obj[key]??'';}n.addEventListener(options?'change':'input',()=>{obj[key]=options?n.value:n.type==='text'?n.value:n.value===''?(nullable?null:null):Number(n.value);this.changed();});wrap.append(n);parent.append(wrap);return n;}
    renderEditor(){const b=this.budget;this.editor.replaceChildren(make('h2','','光源与白点起算'));this.editor.append(make('p','color-note',b.provenance?.scope||'原型假设；需要核对当前器件工况。'));
      const settings=make('div','color-fields');this.field(settings,'目标白点 x',b,'target_x');this.field(settings,'目标白点 y',b,'target_y');this.field(settings,'工作模式',b,'timing',[['sequential','RGB 时序'],['simultaneous','同时点亮 / 调光']]);this.field(settings,'分配方式',b,'allocation',[['solve','求解目标白点'],['manual','手动分配 / 校核']]);this.field(settings,'扣消隐后的可用角度 °',b,'available_angle_deg');['R','G','B'].forEach(g=>this.field(settings,`手动 ${g} 角度 °（同时模式用360°表示满量）`,b.angles_deg,g));this.editor.append(settings,make('p','color-note','求解模式自动分配；手动角度仅在手动模式使用。同一颜色组内的多个光源共用时序。'));
      const sources=make('div','color-sources');b.sources.forEach((s,index)=>{const card=make('details','color-source');card.open=true;card.append(make('summary','',`${index+1}. ${s.name} · ${s.group}`));const fields=make('div','color-fields');this.field(fields,`光源${index+1} 名称`,s,'name');this.field(fields,`光源${index+1} 分组`,s,'group',[['R','R'],['G','G'],['B','B']]);this.field(fields,`光源${index+1} x`,s,'x');this.field(fields,`光源${index+1} y`,s,'y');this.field(fields,`光源${index+1} 输入口径`,s,'input_kind',[['lumens','单颗 lm'],['optical_w','单颗输出光学 W'],['pump_w','单颗泵浦 W']]);this.field(fields,`光源${index+1} 输入值`,s,'input_value');
        const extra=make('details','color-extra');extra.append(make('summary','','工况、功率与来源'));const ef=make('div','color-fields');[['颗数','quantity'],['电流修正倍率','current_factor'],['温度修正倍率','thermal_factor'],['输入面前段效率 0–1','path_efficiency'],['光谱 / 泵浦转换 lm/W','efficacy_lm_per_w'],['同工况单颗电功率 W（可留空）','electrical_w']].forEach(([l,k])=>this.field(ef,`光源${index+1} ${l}`,s,k,null,k==='electrical_w'));this.field(ef,`光源${index+1} 时间口径`,s,'time_basis',[['CW','CW 连续点亮'],['average','全周期已平均']]);this.field(ef,`光源${index+1} 来源`,s,'reference');const enabled=make('label','color-field'),check=make('input');check.type='checkbox';check.checked=s.enabled;check.setAttribute('aria-label',`启用光源${index+1}`);check.addEventListener('change',()=>{s.enabled=check.checked;this.changed();});enabled.append(check,make('span','','启用此光源'));ef.append(enabled,btn('移除此光源',()=>{if(b.sources.length<=3){this.h.toast('至少保留三个光源，分别建立RGB组。',true);return;}b.sources.splice(index,1);this.changed();this.renderEditor();}));extra.append(ef);card.append(fields,extra);sources.append(card);});this.editor.append(sources,btn('＋ 添加光源',()=>{if(b.sources.length>=24)return;const s=clone(b.sources[0]);s.name='新光源 '+(b.sources.length+1);while(b.sources.some(v=>v.name===s.name))s.name+=' +';s.reference='待确认';b.sources.push(s);this.changed();this.renderEditor();}));
      this.editor.append(make('h3','','接收面与屏幕'));const screen=make('div','color-fields');this.field(screen,'输入共同接收面',b,'receiving_plane');this.field(screen,'接收面到屏幕效率 0–1',b,'downstream_efficiency');this.field(screen,'屏幕面积 m²',b,'screen_area_m2');this.field(screen,'观察方向屏幕增益',b,'screen_gain');this.editor.append(screen,make('p','color-note','此效率独立于标量预算，不自动相乘。RGB 选择性损失须放入逐色前段条件，重新求解白点。'));
      this.update();
    }
    async preview(){if(!this.budget)return;const seq=++this.sequence;try{const r=await this.h.api('/api/color/calculate',{budget:clone(this.budget)});if(seq!==this.sequence)return;this.result=r;this.renderResults(r);}catch(e){if(seq!==this.sequence)return;this.results.replaceChildren(make('h2','','无法完成本次预算'),make('p','color-error',e.message));}}
    renderResults(r){this.results.replaceChildren(make('h2','','配色与亮度预算'),make('p','color-note','条件性预测 · 非实测 ANSI / CVIA'));const metrics=make('div','color-metrics');const metric=(label,value,unit)=>{const n=make('div','color-metric');n.append(make('small','',label),make('strong','',fmt(value)),make('span','',unit));metrics.append(n);};metric('输入面光通量合计',r.input_total.lumens,'lm · CW/平均量按输入声明');metric('时序 / 调光后的白场',r.output.lumens,'lm · 输入共同接收面');metric('预测屏幕光通量',r.screen_lumens,'lm');metric('预测平均照度',r.mean_illuminance_lx,'lx');metric('预测方向亮度',r.estimated_luminance_cd_m2,'cd/m²');metric('光源平均电功率',r.average_electrical_w,'W · 非整机功耗');this.results.append(metrics,make('p','color-white',`实际白点 (${fmt(r.output.x,6)}, ${fmt(r.output.y,6)}) · 目标 (${fmt(this.budget.target_x,6)}, ${fmt(this.budget.target_y,6)}) · Δu′v′ ${fmt(r.target_delta_uv_prime,8)}`));
      this.results.append(table(['分组','分配角度 °','占空比 / 调光','平均 lm'],r.rgb.map(v=>[v.group,fmt(v.angle_deg,4),pct(v.weight),fmt(v.average_lumens)])),make('p','color-note',`有效角度 ${fmt(this.budget.available_angle_deg)}°；消隐 ${fmt(360-this.budget.available_angle_deg)}°。平均输入不再乘占空比。`));
      this.results.append(table(['光源','输入面 lm','平均 lm','屏幕 lm'],r.sources.map(v=>[v.name,fmt(v.input_lumens),fmt(v.average_lumens),fmt(v.screen_lumens)])));
      this.results.append(make('h3','','基色范围可视化'));const plots=make('div','color-plots');plots.append(this.plot(r,false),this.plot(r,true));this.results.append(plots,table(['参考 / 坐标','面积比','交集覆盖'],Object.entries(r.gamut).flatMap(([name,g])=>[['xy','uv_prime'].map(k=>[name+' · '+(k==='xy'?'xy':'u′v′'),pct(g[k].area_ratio),pct(g[k].intersection_coverage)])].flat())),make('p','color-note','面积比可以超过100%；交集覆盖不超过100%。图中只画基色三角形，不代表光谱轨迹、色容积或色准。'));
      this.results.append(table(['有条件的电热指标','结果'],[['屏幕 lm / 光源电学 W',fmt(r.screen_lm_per_electrical_w)],['源级电光差值热功率 W',fmt(r.source_heat_w)]]));const warnings=make('ul','color-warnings');r.warnings.forEach(w=>warnings.append(make('li','',w)));this.results.append(warnings);const notes=make('details','color-assumptions');notes.append(make('summary','','公式、单位与适用条件'));const formulas=make('p','color-note','X=x·Y/y，Z=(1−x−y)·Y/y，Y=lm；各源XYZ先相加。时序平均量=CW量×角度/360°。屏幕lm=白场lm×后段η；平均lx=lm/m²；方向cd/m²=lm×增益/(π×m²)。');const a=make('ul');r.assumptions.forEach(w=>a.append(make('li','',w)));notes.append(formulas,a);this.results.append(notes);}
    plot(r,isUV){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 300 285');svg.setAttribute('role','img');svg.setAttribute('aria-label',isUV?'u′v′基色三角形与白点':'xy基色三角形与白点');const convert=p=>{if(!isUV)return p;const d=-2*p[0]+12*p[1]+3;return[4*p[0]/d,9*p[1]/d];};const max=isUV?[.65,.65]:[.8,.9],point=p=>[35+p[0]/max[0]*245,245-p[1]/max[1]*210];const draw=(tag,attrs,text)=>{const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));if(text)n.textContent=text;svg.append(n);return n;};draw('text',{x:35,y:20},isUV?'CIE 1976 u′v′':'CIE 1931 xy');for(let i=0;i<=4;i++){const x=35+i*245/4,y=245-i*210/4;draw('line',{x1:35,y1:y,x2:280,y2:y,class:'color-plot-grid'});draw('text',{x:3,y:y+4},fmt(i*max[1]/4,2));draw('text',{x:x-7,y:267},fmt(i*max[0]/4,2));}draw('line',{x1:35,y1:35,x2:35,y2:245,class:'color-axis'});Object.entries(r.gamut).forEach(([name,v])=>draw('polygon',{points:v[isUV?'uv_prime':'xy'].reference.map(point).map(p=>p.join(',')).join(' '),class:name==='DCI-P3'?'color-ref-p3':'color-ref-709'}));draw('polygon',{points:r.grouped.map(g=>point(convert([g.x,g.y]))).map(p=>p.join(',')).join(' '),class:'color-triangle'});r.grouped.forEach(g=>{const[x,y]=point(convert([g.x,g.y]));draw('circle',{cx:x,cy:y,r:4,class:'color-point-'+g.group});draw('text',{x:x+7,y:y},g.group);});const t=point(convert([this.budget.target_x,this.budget.target_y]));draw('circle',{cx:t[0],cy:t[1],r:6,class:'color-target'});if(r.output.x!==null){const a=point(convert([r.output.x,r.output.y]));draw('path',{d:`M ${a[0]-4} ${a[1]} h 8 M ${a[0]} ${a[1]-4} v 8`,class:'color-actual'});}const wrap=make('div');wrap.append(svg,make('p','color-note','实线：当前RGB；蓝虚线：P3；灰虚线：BT.709；○目标，＋输出。'));return wrap;}
    async readCase(id){const seq=++this.caseSequence;this.case=null;this.caseBody.textContent='正在读取已核读案例…';this.update();try{const c=await this.h.api('/api/color/cases/'+encodeURIComponent(id));if(seq!==this.caseSequence)return;this.case=c;this.caseBody.replaceChildren(make('p','color-note',c.scope),table(['口径','白场 lm','x','y'],[['原表缓存',fmt(c.original.white_lumens),fmt(c.original.x,6),fmt(c.original.y,6)],['保留原角度 · 同源坐标复算',fmt(c.comparison.same_original_angles.lumens),fmt(c.comparison.same_original_angles.x,6),fmt(c.comparison.same_original_angles.y,6)],['目标白点精确求解',fmt(c.comparison.solved.lumens),fmt(c.comparison.solved.x,6),fmt(c.comparison.solved.y,6)]]),make('p','color-white',`原表CW合计 ${fmt(c.original.cw_lumens)} lm → 全部光源合计 ${fmt(c.comparison.input_total_lumens)} lm`));
        if(c.original.cie1976_labeled_P3_ratio!=null)this.caseBody.append(make('p','color-note',`原“CIE1976/P3”标签 ${pct(c.original.cie1976_labeled_P3_ratio)}；独立 u′v′ 面积比 ${pct(c.comparison.solved.gamut['DCI-P3'].uv_prime.area_ratio)}。面积比不等于覆盖。`));
        const audit=make('details','color-assumptions');audit.append(make('summary','',`查看 ${c.audit.length} 项单元格核读与功率问题`));if(c.audit.length)audit.append(table(['来源定位','核读发现与处理'],c.audit.map(a=>[a.location,a.finding])));
        if(c.original.power_rows?.length)audit.append(table(['历史功率行','光学 W','电学 W','电学W×原WPE所得光学W'],c.original.power_rows.map(p=>[p.row,fmt(p.optical_W_at_CW),fmt(p.electrical_W_recorded),fmt(p.optical_W_from_recorded_WPE)])));
        this.caseBody.append(audit);const foot=make('details','color-assumptions');foot.append(make('summary','','来源编号与文件指纹'),make('p','color-note',`${c.source_id} / ${c.sheet||'合成演示'} / SHA-256 ${c.source_sha256||'不适用'}`));if(c.reference_slug)foot.append(btn('阅读完整核读依据',()=>this.h.reference(c.reference_slug)));this.caseBody.append(foot);
      }catch(e){if(seq===this.caseSequence)this.caseBody.textContent=e.message;}this.update();}
    applyCase(){if(!this.case||this.h.state().busy)return;this.budget=clone(this.case.budget);this.changed();this.renderEditor();this.h.toast('已载入案例作为原型假设；修改屏幕条件后保存。');}
  }
  window.ColorView=ColorView;
})();
